// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGJFiKZ_zRVE1pKHmyayapTi5iTTmpQM',
    appId: '1:696576313674:web:46911bc1fece46254099b3',
    messagingSenderId: '696576313674',
    projectId: 'edu-ticket',
    authDomain: 'edu-ticket.firebaseapp.com',
    storageBucket: 'edu-ticket.appspot.com',
    measurementId: 'G-ES1F6QR9F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlelfLgkvQw3Ao0Nwpiw_ibTfXex-MR0',
    appId: '1:696576313674:android:bb1c8482f4567e964099b3',
    messagingSenderId: '696576313674',
    projectId: 'edu-ticket',
    storageBucket: 'edu-ticket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOXPghA8WAUTPbB-35cluJj4eYU3dQoN4',
    appId: '1:696576313674:ios:49eb281834ef48454099b3',
    messagingSenderId: '696576313674',
    projectId: 'edu-ticket',
    storageBucket: 'edu-ticket.appspot.com',
    iosBundleId: 'com.example.eduticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOXPghA8WAUTPbB-35cluJj4eYU3dQoN4',
    appId: '1:696576313674:ios:49eb281834ef48454099b3',
    messagingSenderId: '696576313674',
    projectId: 'edu-ticket',
    storageBucket: 'edu-ticket.appspot.com',
    iosBundleId: 'com.example.eduticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuGJFiKZ_zRVE1pKHmyayapTi5iTTmpQM',
    appId: '1:696576313674:web:260a840a4ffe215c4099b3',
    messagingSenderId: '696576313674',
    projectId: 'edu-ticket',
    authDomain: 'edu-ticket.firebaseapp.com',
    storageBucket: 'edu-ticket.appspot.com',
    measurementId: 'G-LZVG1MS8LZ',
  );
}
